name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
        include-prerelease: true

    - name: Restore dependencies
      run: dotnet restore

    - name: Build with dotnet
      run: dotnet build --no-restore
      
    - name: List Test Directory Contents
      run: ls -R CourseSubmission_Project_ManeroApp/Manero.Tests

    - name: Run Tests
      run: dotnet test --no-build --no-restore --verbosity normal 
