name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
        include-prerelease: true

    - name: Restore dependencies
      run: dotnet restore

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Run Tests
      run: dotnet test Manero.Tests/Manero.Tests.csproj --no-build --no-restore --verbosity normal --logger "trx;LogFileName=minTestLogg.trx"
